# 站点基本信息
title: "大拿的学习教程"
description: "关于编程，特别是Python变成的内容，本人复制/编写而来"
baseurl: ""
url: "https://danalaoshi.github.io"

# 远程主题
remote_theme: pmarsceill/just-the-docs

# 插件
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock

# Just the Docs 配置
search_enabled: true
search:
  heading_level: 2
  previews: 3

#aux_links:
#  "在 GitHub 上查看":
#    - "//github.com/danalaoshi/danalaoshi.github.io"

# 颜色主题
color_scheme: "light"
logo: "/_data/images/logo.png"
favicon: "/_data/images/fav.ico"
# 导航配置
heading_anchors: true

# 集合配置
collections:
  books:
    output: true
    permalink: /:path/

# 默认值
defaults:
  - scope:
      path: ""
      type: "books"
    values:
      layout: "default"
      nav_exclude: false
  - scope:
      path: ""
    values:
      layout: "default"
      nav_exclude: false