# 站点基本信息
title: "编程教程中心"
description: "全面的编程学习资源库"
baseurl: ""  # 如果是项目页面，填写 "/repository-name"
url: "https://yourusername.github.io"  # 你的 GitHub Pages 地址
github_username: yourusername

# 构建设置
markdown: kramdown
highlighter: rouge
permalink: pretty

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

# 使用 Material for MkDocs 风格的远程主题
remote_theme: squidfunk/mkdocs-material

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .github/

# 包含文件
include:
  - _layouts
  - _includes
  - _sass
  - assets

# 自定义集合 - 书籍
collections:
  books:
    output: true
    permalink: /:path/

# 默认布局
defaults:
  - scope:
      path: ""
      type: "books"
    values:
      layout: "book"
  - scope:
      path: ""
    values:
      layout: "default"

# Material 主题配置
material:
  # 调色板
  palette:
    primary: indigo
    accent: indigo

  # 字体
  font:
    text: Roboto
    code: Roboto Mono

  # 功能特性
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.sections
    - toc.integrate

# 书籍自动发现配置
books:
  - name: "Python 编程"
    dir: "python"
    icon: "code"
    order: 1
  - name: "Java 编程"
    dir: "java"
    icon: "coffee"
    order: 2
  - name: "人工智能"
    dir: "AI"
    icon: "smart_toy"
    order: 3

# 搜索配置
search:
  enabled: true
  provider: lunr

# 作者信息
author:
  name: "刘大拿"
  email: "your-email@example.com"

# 社交链接
social:
  github: yourusername
  email: your-email@example.com

# 构建时变量
sass:
  style: compressed